MH-8471 Modified check-prerequisites for CentOS and RHEL to check for OS version (5/6) and use yum wherever possible
git-svn-id: https://opencast.jira.com/svn/MH/trunk@11726 e6edf6fb-f266-4316-afb4-e53d95876a76

diff --git a/docs/scripts/3rd_party/utilx b/docs/scripts/3rd_party/utilx
--- a/docs/scripts/3rd_party/utilx
+++ b/docs/scripts/3rd_party/utilx
@@ -4,11 +4,7 @@
 #
 case `uname` in
   Linux )
-    [ -s /etc/issue ] && awk '{
-  if (length($0) == 0) next;
-  print $0;
-  exit 0
-}' /etc/issue
+    [ -s /etc/issue ] && awk '{if (length($0) == 0) next; print $0; exit 0}' /etc/issue
     uname -smr
     export LOCAL_PREFIX=/usr/local
     ;;
@@ -28,13 +24,21 @@ unset CDPATH
 #   $1 = "on"/"off"
 #
 echox() {
-  ECHO=`set -o | awk '/^xtrace/{print $2}'`
+  ECHO=`set -o | awk '/^xtrace/ {print $2}'`
   if [ "$ECHO" = "on" ]; then
     [ "$1" = "off" ] && set +x
   else
     [ "$1" = "on" ] && set -x
   fi
   echo $ECHO
+}
+#
+# full path of file(s)
+#
+fullpath() {
+  for file in "$@"; do
+    readlink -f "$file"
+  done
 }
 #
 # arch
@@ -157,22 +161,37 @@ chklib() {
   case `uname` in
     Linux )
       for dir in /lib /usr/lib /lib/tls /lib/i686 /lib/tls/i686 /usr/lib/sse2 /usr/lib/tls; do
-        [ -s "$dir/lib$1.so" ] && return 0
+        LIBSO="$dir/lib$1.so $dir/lib$1.so.[0-9]*"
+        for file in $LIBSO; do
+          [ -s "$file" ] && return 0
+        done
       done
       for dir in /lib64 /usr/lib64 /lib64/tls /lib64/i686 /lib64/tls/i686 /usr/lib64/sse2 /usr/lib64/tls; do
-        [ -s "$dir/lib$1.so" ] && return 0
+        LIBSO="$dir/lib$1.so $dir/lib$1.so.[0-9]*"
+        for file in $LIBSO; do
+          [ -s "$file" ] && return 0
+        done
       done
 #     for dir in /lib/i386-linux-gnu /usr/lib/i386-linux-gnu /lib/i486-linux-gnu /usr/lib/i486-linux-gnu /lib/i586-linux-gnu /usr/lib/i586-linux-gnu /lib/i686-linux-gnu /usr/lib/i686-linux-gnu; do
-#       [ -s "$dir/lib$1.so" ] && return 0
+#       LIBSO="$dir/lib$1.so $dir/lib$1.so.[0-9]*"
+#       for file in $LIBSO; do
+#         [ -s "$file" ] && return 0
+#       done
 #     done
 #     for dir in /lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu; do
-#       [ -s "$dir/lib$1.so" ] && return 0
+#       LIBSO="$dir/lib$1.so $dir/lib$1.so.[0-9]*"
+#       for file in $LIBSO; do
+#         [ -s "$file" ] && return 0
+#       done
 #     done
       echo "lib$1.so is missing" 1>&2
       ;;
     Darwin )
       for dir in /lib /usr/lib /opt/local/lib /usr/local/lib ~/lib; do
-        [ -s "$dir/lib$1.dylib" ] && return 0
+        LIBSO="$dir/lib$1.dylib"
+        for file in $LIBSO; do
+          [ -s "$file" ] && return 0
+        done
       done
       echo "lib$1.dylib is missing" 1>&2
       ;;
@@ -208,6 +227,24 @@ chkinc() {
         [ -n "$FILE" ] && return 0
       done
       echo "$1 is missing" 1>&2
+      ;;
+  esac
+  return 1
+}
+#
+# chkrepo
+#   $1 = repository to check
+#
+chkrepo() {
+  case `uname` in
+    Linux )
+      sudox yum repolist | grep "^$1"
+      [ ${PIPESTATUS[1]} -eq 0 ] && return 0
+      echo "Repository $1 is missing" 1>&2
+      ;;
+    Darwin )
+      return 0
+      echo "Repository $1 is missing" 1>&2
       ;;
   esac
   return 1
@@ -364,7 +401,7 @@ download() {
   else
     if [ -f config.txt ]; then
       for ii in "" 1 2 3; do
-        ppos=0
+        typeset -i ppos=0
         for pkg in `getcfg PKG${ii}:`; do
           let ppos=ppos+1
           if [ ! -s "$pkg" ]; then
@@ -381,7 +418,7 @@ download() {
                 return 1
               else
                 shas=`getcfg SHA${ii}:`
-                sha=""; jj=0
+                sha=""; typeset -i jj=0
                 for sha in $shas; do
                   let jj=jj+1
                   [ $jj -eq $ppos ] && break
@@ -506,6 +543,18 @@ EOF
   fi
   set -x
   return $RC
+}
+#
+# yumx
+#   $@ = yum command line
+#
+yumx() {
+  rm -f /tmp/yumx.log
+  sudox yum "$@" 2>&1 | tee /tmp/yumx.log
+  [ ${PIPESTATUS[0]} -ne 0 ] && return 1
+  grep "No package .* available." /tmp/yumx.log
+  [ $? -eq 0 ] && return 1
+  return 0
 }
 #
 # copypc
